import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import typedocSidebar from './docs/api/typedoc-sidebar';

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: 'Typedoc API',
      link: {
        type: 'doc',
        id: 'api/index',
      },
      items: typedocSidebar.items,
    },
  ],
  aboutSidebar: [
    {
      type: 'category',
      label: 'About',
      items: [{ type: 'autogenerated', dirName: 'about' }],
    },
  ],
};

export default sidebars;
